version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python example.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install PIPENV
          command: |
            sudo pip install pipenv
      - run:
          name: Install Packages with Developer Tools
          command: |
            pipenv install --dev
      - run:
          name: CircleCI Test Summary
          command: |
            mkdir test-reports
            pipenv run pytest --junitxml=test-reports/junit.xml
      - run:
          name: Coveralls
          command: |
            pipenv run pytest --cov=./investment/
            pipenv run coveralls
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
