version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python example.py
          sudo pip install pytest pytest-cov coveralls
          mkdir test-reports
          pytest --junitxml=test-reports/junit.xml
          pytest --cov=./
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - post:
          - coveralls
