version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python example.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install Test Tools
          command: |
            sudo pip install pytest pytest-cov coveralls
      - run:
          name: CircleCI Test Summary
          command: |
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml
      - run:
          name: Coveralls
          command: |
            pytest --cov=./
            coveralls
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
        requires:
          - test
