version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python example.py
          sudo pip install coverage
          mkdir test-reports
          coverage run -m unittest discover -s tests/
          coverage report && coverage xml -o test-reports/coverage.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
