version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python example.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install PIPENV
          command: |
            sudo pip install pipenv
      - run:
          name: Install Packages with Developer Tools
          command: |
            pipenv install --dev
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: CircleCI Test Summary
          command: |
            mkdir test-reports
            pipenv run pytest --junitxml=test-reports/junit.xml
      - run:
          name: Coveralls
          command: |
            pipenv run pytest --cov=./investment/
            pipenv run coveralls
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
